name: Upload Release Asset

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/autamus/go
      options: --entrypoint /bin/bash
    steps:
      - name: Setup Environment
        run: |
          apt-get update 
          apt-get install -y git wget
          wget https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz
          tar -xzvf hub-linux-amd64-2.14.2.tgz
          ./hub-linux-amd64-2.14.2/install
          rm /opt/view/bin/git
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          chmod a+x .github/workflows/build.sh
          ./.github/workflows/build.sh ${GITHUB_REF##*/}
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod a+x .github/workflows/release.sh
          ./.github/workflows/release.sh